# Generated by Django 5.2.5 on 2025-11-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número da pergunta (ex: 1, 2, 3)', unique=True)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text="Ex: 'SIM' ou 'NÃO'", max_length=10)),
                ('risco_resultante', models.CharField(help_text="Ex: 'III', 'II', 'I', 'NA'", max_length=10)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='simulador_risco.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=512)),
                ('risco_base', models.CharField(help_text='I, II, III, NA, ou P', max_length=10)),
                ('perguntas', models.ManyToManyField(blank=True, help_text="Perguntas associadas se o risco_base for 'P'", to='simulador_risco.pergunta')),
            ],
        ),
    ]
