# Generated by Django 5.2.5 on 2025-11-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_risco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnae',
            name='dispensado_de_projeto',
            field=models.BooleanField(default=False, help_text='Marca se uma atividade de Risco III é dispensada de aprovação de projeto arquitetônico (Anexo III)'),
        ),
    ]
