# Generated by Django 5.2.5 on 2025-11-26 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_risco', '0002_cnae_dispensado_de_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_agregacao', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_dn_copam', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_atividade', models.TextField(verbose_name='Descrição da Atividade Ambiental')),
                ('exigencia_municipal', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_risco', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes_ambientais', to='simulador_risco.cnae')),
            ],
        ),
    ]
