# Generated by Django 5.2.5 on 2025-08-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='ferramentas_contratadas',
            field=models.ManyToManyField(blank=True, to='gestao.ferramenta', verbose_name='Ferramentas Contratadas'),
        ),
    ]
