# Generated by Django 5.2.5 on 2025-09-24 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0002_ferramenta_empresa_ferramentas_contratadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Cabeça e Pescoço, Tórax...', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CID10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código CID-10')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Doença (CID-10)',
                'verbose_name_plural': 'Doenças (CID-10)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Leito')),
            ],
            options={
                'verbose_name': 'Leito',
                'verbose_name_plural': 'Leitos',
            },
        ),
        migrations.CreateModel(
            name='Ala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ala')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alas', to='gestao.empresa')),
            ],
            options={
                'verbose_name': 'Ala',
                'verbose_name_plural': 'Alas',
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='AreaEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Crânio, Couro Cabeludo...', max_length=100)),
                ('area_corporal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_especificas', to='gestao_hospitalar.areacorporal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_especificas', to='gestao.empresa')),
            ],
            options={
                'unique_together': {('nome', 'area_corporal', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='AchadoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Assimetria, Presença de lesões...', max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados_clinicos', to='gestao.empresa')),
                ('area_especifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados_clinicos', to='gestao_hospitalar.areaespecifica')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoNANDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('definicao', models.TextField()),
                ('achados_relacionados', models.ManyToManyField(blank=True, related_name='diagnosticos_sugeridos', to='gestao_hospitalar.achadoclinico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_nanda', to='gestao.empresa')),
            ],
            options={
                'unique_together': {('codigo', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='IntervencaoNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('definicao', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes_nic', to='gestao.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('intervencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='gestao_hospitalar.intervencaonic')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo do Paciente')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('diagnosticos_complementares', models.ManyToManyField(blank=True, related_name='pacientes_com_diag_complementar', to='gestao_hospitalar.cid10', verbose_name='Diagnósticos Complementares (CID-10)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='gestao.empresa')),
                ('hipotese_diagnostica_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_com_diag_principal', to='gestao_hospitalar.cid10', verbose_name='Hipótese Diagnóstica (CID-10 Principal)')),
                ('leito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_alocado', to='gestao_hospitalar.leito')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoSAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_finalizada', models.BooleanField(default=False)),
                ('achados_selecionados', models.ManyToManyField(blank=True, to='gestao_hospitalar.achadoclinico')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagnostico_nanda_selecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_hospitalar.diagnosticonanda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_sae', to='gestao_hospitalar.paciente')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Quarto')),
                ('ala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='gestao_hospitalar.ala')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'unique_together': {('numero', 'ala')},
            },
        ),
        migrations.AddField(
            model_name='leito',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='gestao_hospitalar.quarto'),
        ),
        migrations.CreateModel(
            name='ResultadoNOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('definicao', models.TextField()),
                ('diagnosticos_nanda', models.ManyToManyField(blank=True, related_name='resultados_noc', to='gestao_hospitalar.diagnosticonanda')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_noc', to='gestao.empresa')),
            ],
            options={
                'unique_together': {('codigo', 'empresa')},
            },
        ),
        migrations.AddField(
            model_name='intervencaonic',
            name='resultados_noc',
            field=models.ManyToManyField(blank=True, related_name='intervencoes_nic', to='gestao_hospitalar.resultadonoc'),
        ),
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Inspeção, Palpação...', max_length=100, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_exame', to='gestao.empresa')),
            ],
            options={
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.AddField(
            model_name='achadoclinico',
            name='tipo_exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados_clinicos', to='gestao_hospitalar.tipoexame'),
        ),
        migrations.CreateModel(
            name='AvaliacaoFugulin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now)),
                ('estado_mental', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Estado Mental')),
                ('oxigenacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Oxigenação')),
                ('sinais_vitais', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Sinais Vitais')),
                ('motilidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Motilidade')),
                ('deambulacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Deambulação')),
                ('alimentacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Alimentação')),
                ('cuidado_corporal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Cuidado Corporal')),
                ('eliminacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Eliminação')),
                ('terapeutica', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Terapêutica')),
                ('pontuacao_total', models.IntegerField(editable=False, null=True)),
                ('categoria_cuidado', models.CharField(editable=False, max_length=50, null=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fugulin', to='gestao_hospitalar.paciente')),
            ],
            options={
                'verbose_name': 'Avaliação (Fugulin)',
                'verbose_name_plural': 'Avaliações (Fugulin)',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('paciente', 'data_avaliacao')},
            },
        ),
        migrations.CreateModel(
            name='PlanoCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso_atividades', models.JSONField(blank=True, default=dict)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_de_cuidados', to='gestao_hospitalar.avaliacaosae')),
                ('intervencao_nic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_hospitalar.intervencaonic')),
            ],
            options={
                'unique_together': {('avaliacao', 'intervencao_nic')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='leito',
            unique_together={('numero', 'quarto')},
        ),
        migrations.AlterUniqueTogether(
            name='intervencaonic',
            unique_together={('codigo', 'empresa')},
        ),
    ]
