# Generated by Django 5.2.5 on 2025-09-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0002_ferramenta_empresa_ferramentas_contratadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CID10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código CID-10')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Doença (CID-10)',
                'verbose_name_plural': 'Doenças (CID-10)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Leito')),
            ],
            options={
                'verbose_name': 'Leito',
                'verbose_name_plural': 'Leitos',
            },
        ),
        migrations.CreateModel(
            name='Ala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ala')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alas', to='gestao.empresa')),
            ],
            options={
                'verbose_name': 'Ala',
                'verbose_name_plural': 'Alas',
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo do Paciente')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('diagnosticos_complementares', models.ManyToManyField(blank=True, related_name='pacientes_com_diag_complementar', to='gestao_hospitalar.cid10', verbose_name='Diagnósticos Complementares (CID-10)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='gestao.empresa')),
                ('hipotese_diagnostica_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_com_diag_principal', to='gestao_hospitalar.cid10', verbose_name='Hipótese Diagnóstica (CID-10 Principal)')),
                ('leito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_alocado', to='gestao_hospitalar.leito')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Quarto')),
                ('ala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='gestao_hospitalar.ala')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'unique_together': {('numero', 'ala')},
            },
        ),
        migrations.AddField(
            model_name='leito',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='gestao_hospitalar.quarto'),
        ),
        migrations.AlterUniqueTogether(
            name='leito',
            unique_together={('numero', 'quarto')},
        ),
    ]
