# Generated by Django 5.2.5 on 2025-09-16 02:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_hospitalar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFugulin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now)),
                ('estado_mental', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Estado Mental')),
                ('oxigenacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Oxigenação')),
                ('sinais_vitais', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Sinais Vitais')),
                ('motilidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Motilidade')),
                ('deambulacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Deambulação')),
                ('alimentacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Alimentação')),
                ('cuidado_corporal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Cuidado Corporal')),
                ('eliminacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Eliminação')),
                ('terapeutica', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Terapêutica')),
                ('pontuacao_total', models.IntegerField(editable=False, null=True)),
                ('categoria_cuidado', models.CharField(editable=False, max_length=50, null=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fugulin', to='gestao_hospitalar.paciente')),
            ],
            options={
                'verbose_name': 'Avaliação (Fugulin)',
                'verbose_name_plural': 'Avaliações (Fugulin)',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('paciente', 'data_avaliacao')},
            },
        ),
    ]
