# Generated by Django 5.2.5 on 2025-09-21 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_hospitalar', '0002_avaliacaofugulin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntervencaoNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('definicao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_corporal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_especificas', to='gestao_hospitalar.areacorporal')),
            ],
        ),
        migrations.CreateModel(
            name='AchadoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo_exame', models.CharField(choices=[('INSPECAO', 'Inspeção'), ('PALPACAO', 'Palpação'), ('AUSCULTA', 'Ausculta'), ('PERCUSSAO', 'Percussão')], max_length=10)),
                ('area_especifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados_clinicos', to='gestao_hospitalar.areaespecifica')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoNANDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('definicao', models.TextField()),
                ('achados_relacionados', models.ManyToManyField(blank=True, related_name='diagnosticos_sugeridos', to='gestao_hospitalar.achadoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoSAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_finalizada', models.BooleanField(default=False)),
                ('achados_selecionados', models.ManyToManyField(blank=True, to='gestao_hospitalar.achadoclinico')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_sae', to='gestao_hospitalar.paciente')),
                ('diagnostico_nanda_selecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_hospitalar.diagnosticonanda')),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('intervencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='gestao_hospitalar.intervencaonic')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoNOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('definicao', models.TextField()),
                ('diagnosticos_nanda', models.ManyToManyField(blank=True, related_name='resultados_noc', to='gestao_hospitalar.diagnosticonanda')),
            ],
        ),
        migrations.AddField(
            model_name='intervencaonic',
            name='resultados_noc',
            field=models.ManyToManyField(blank=True, related_name='intervencoes_nic', to='gestao_hospitalar.resultadonoc'),
        ),
        migrations.CreateModel(
            name='PlanoCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso_atividades', models.JSONField(blank=True, default=dict)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_de_cuidados', to='gestao_hospitalar.avaliacaosae')),
                ('intervencao_nic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_hospitalar.intervencaonic')),
            ],
            options={
                'unique_together': {('avaliacao', 'intervencao_nic')},
            },
        ),
    ]
